### PR TITLE
Fix UUID schema error

### LINKED ISSUE #76: Column UUID caused schema error on upgrade
**Describe the bug**
column uuid caused schema error

**To Reproduce**

1. for plugin users who installed this plugin before this version 2011072600
2. run `php admin/cli/check_database_schema.php`
3. Will see error of:

```
equella
 * column 'uuid' has incorrect type 'X', expected 'C'
```

**Expected behavior**

```
root@44bc1ff7eaf7:/siteroot# php admin/cli/check_database_schema.php
Database structure is ok.
```

**Stacktrace**

n/a

**Platform:**

- openEQUELLA Version: [e.g. 6.5, 6.6]
- Moodel Version: 35

### PR DESCRIPTION
**Pull request by yao9394**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [ ] commit message follows [commit guidelines][]
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

#76

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-ian** [comment]
Hello @yao9394 

Thank you very much for you contribution. We'll review it shortly.

Could you please advise whether have or if you're able to to sign the  [contributor license agreement](https://www.apereo.org/node/676)? Apereo requires this before contributions can be accepted.  (If you have already done so, the process is quick and painless.)

**Comment by yao9394** [comment]
> Hello @yao9394
> 
> Thank you very much for you contribution. We'll review it shortly.
> 
> Could you please advise whether have or if you're able to to sign the [contributor license agreement](https://www.apereo.org/node/676)? Apereo requires this before contributions can be accepted. (If you have already done so, the process is quick and painless.)

Hi @edalex-ian , thanks. I have just signed the agreement

**Comment by edalex-ian** [comment]
Thanks @yao9394 . Please let us know when you've received acceptance. :)

**Comment by ChristianMurphy** [comment]
@edalex-ian the ICLA is now listed on http://licensing.apereo.org, under the GitHub tab, thanks @yao9394!

**Comment by edalex-ian** [comment]
Heya @SammyIsConfused 

As we look towards a 1.2 for #80 , could you please review and validate this?

Thank you.

**Comment by PenghaiZhang** [comment]
Thanks @yao9394 for this PR. I am trying to validate this fix but I have a few questions here.

1. In #76, you mentioned `for plugin users who installed this plugin before this version 2011072600`. However, as far as I know, this plugin requires Moodle 2.7 and up. Moodle 2.7 was released in 2014. So how can plugin users install this plugin with a Moodle version released in 2011 ?

2. What database were you using for Moodle ? 

3. Were you using Equella 6.6 or 6.5 or other newer version ?

**Pull request closed without merging**
